/**
 * This file is auto-generated by protobuf
 * Don't change manually
 */

import webapi from "../webapi";

export enum SectionType {
  cat = "cat",
  brand = "brand",
}


export interface CategoryItem {
  id: number
  name: string
  image: string
  url: string
}

export interface SectionCategory {
  id: string
  type: SectionType
  name: string
  categories: CategoryItem[]
}

export interface SideItem {
  id: string
  name: string
}

export interface CategoryListRequest {
  sideId: string
}

export interface CategoryListResponse {
  sideItems: SideItem[]
  sectionCategoryList: SectionCategory[]
}



export function CategoryList(payload: CategoryListRequest) {
  return webapi<CategoryListResponse>("category.Category/CategoryList", payload);
}

export default {
  CategoryList,
}