/**
 * This file is auto-generated by protobuf
 * Don't change manually
 */

import { ProductItem as ProductProductItem } from "./product";
import webapi from "../webapi";

export enum SectionType {
  cat = "cat",
  brand = "brand",
}


export interface CategoryItem {
  id: number
  name: string
  image: string
  url: string
}

export interface SectionCategory {
  id: string
  type: SectionType
  name: string
  categories: CategoryItem[]
}

export interface SideItem {
  id: string
  name: string
}

export interface CategoryListRequest {
  sideId: string
}

export interface CategoryListResponse {
  sideItems: SideItem[]
  sectionCategoryList: SectionCategory[]
}

export interface CategoryProductsRequest {
  categoryId: number
  limit: number
  offset: number
}

export interface CategoryProductsResponse {
  products: ProductProductItem[]
  total: number
}



export function CategoryList(payload: CategoryListRequest) {
  return webapi<CategoryListResponse>("category.Category/CategoryList", payload);
}
export function CategoryProducts(payload: CategoryProductsRequest) {
  return webapi<CategoryProductsResponse>("category.Category/CategoryProducts", payload);
}

export default {
  CategoryList,
  CategoryProducts,
}