/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import webapi from "../webapi";

export interface Empty {

}

export interface Nav {
	name: string;
	image: string;
	url: string;
}

export interface Banner {
	title: string;
	image: string;
	url: string;
}

export interface WindowResponse {
	navs: Nav[];
	banners: Banner[];
}



export function Window(payload: Partial<Empty>) {
	return webapi<WindowResponse>("homepage.Homepage/Window", payload);
}


export default {
	Window,
};