/**
 * This file is auto-generated by protobuf
 * Don't change manually
 */

import webapi from "../webapi";

export interface ProductItem {
  id: number
  price: string
  title: string
  url: string
  image: string
}

export interface ProductListRequest {
  shopId: string
  limit: number
  offset: number
}

export interface ProductListResponse {
  products: ProductItem[]
  total: number
  shopId: string
  shopName: string
}



export function ProductList(payload: ProductListRequest) {
  return webapi<ProductListResponse>("product.Product/ProductList", payload);
}

export default {
  ProductList,
}