/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import webapi from "../webapi";

export interface ProductItem {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	id: number;
	price: string;
	name: string;
	url: string;
	image: string;
}

export interface ProductListRequest {
	shopId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface ProductListResponse {
	products: ProductItem[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	shopId: string;
	shopName: string;
}



export function ProductList(payload: Partial<ProductListRequest>) {
	return webapi<ProductListResponse>("product.Product/ProductList", payload);
}


export default {
	ProductList,
};