/**
 * This file is auto-generated by protobuf
 * Don't change manually
 */

import webapi from "../webapi";

export interface TodoItem {
  id: string
  name: string
  complete: boolean
}

export interface TodoListRequest {
  uid: number
}

export interface TodoListResponse {
  list: TodoItem[]
}



export function List(payload: TodoListRequest) {
  return webapi<TodoListResponse>("todo.Todo/List", payload);
}

export default {
  List,
}